import {test, beforeEach, afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker, {validate,processEmails,emailPayloads,organiserForCity} from '../worker.mjs';
import events from '../../../ppsmutual/events.json' with {type:'json'};
class D1 {
  constructor(){this.db=new DatabaseSync(':memory:');this.db.exec(readFileSync(new URL('../migrations/0001.sql',import.meta.url),'utf8'));}
  prepare(sql){const db=this.db;let params=[];const api={bind(...p){params=p;return api;},async first(){return db.prepare(sql).get(...params) || null;},async all(){return {results:db.prepare(sql).all(...params)};},async run(){return {meta:db.prepare(sql).run(...params)};}};return api;}
  async batch(statements){this.db.exec('BEGIN');try{const result=[];for(const statement of statements)result.push(await statement.run());this.db.exec('COMMIT');return result;}catch(e){this.db.exec('ROLLBACK');throw e;}}
}
const originalFetch=globalThis.fetch;
const originalNow=Date.now;
let env,requests,tasks;
const data={city:'brisbane',firstName:'Alex',lastName:'Example',email:'ALEX@example.com',organisation:'Example Advice',phone:'',dietary:'vegetarian',dietaryNotes:'',consent:true,turnstileToken:'test-token',website:''};
const key='test-request-0000000000000001';
const ctx={waitUntil(p){tasks.push(p);}};
function req(body=data,headers={}){return new Request('https://api.example.com/registrations',{method:'POST',headers:{Origin:'https://chargeout.net','Content-Type':'application/json','Idempotency-Key':key,...headers},body:JSON.stringify(body)});}
beforeEach(()=>{Date.now=()=>new Date('2026-10-06T03:00:00Z').getTime();tasks=[];requests=[];env={DB:new D1(),REGISTRATION_OPEN:'true',NOTIFICATION_MODE:'full',RESEND_API_KEY:'fake-key',TURNSTILE_SECRET:'fake-secret',ADMIN_TOKEN:'test-only-access-key-at-least-32-characters',EMAIL_FROM:'Adviser Connect <info@chargeout.net>',ORGANISER_EMAILS:JSON.stringify({brisbane:'brisbane-organiser@example.com',perth:'perth-organiser@example.com',melbourne:'melbourne-organiser@example.com'})};globalThis.fetch=async(url,options)=>{requests.push({url,options});return String(url).includes('siteverify')?Response.json({success:true,hostname:'chargeout.net'}):Response.json({id:'email-test-id'});};});
afterEach(async()=>{await Promise.all(tasks);env.DB.db.close();globalThis.fetch=originalFetch;Date.now=originalNow;});
test('server rejects missing consent, malformed email and unsupported dietary choices',()=>{assert.throws(()=>validate({...data,consent:false}));assert.throws(()=>validate({...data,email:'bad'}));assert.throws(()=>validate({...data,dietary:'invalid'}));assert.equal(validate(data).email,'alex@example.com');});
test('city alerts route only to the configured state recipient',()=>{const expected={brisbane:'brisbane-organiser@example.com',perth:'perth-organiser@example.com',melbourne:'melbourne-organiser@example.com'};for(const event of events.cities){assert.equal(organiserForCity(env,event.id),expected[event.id]);const jobs=emailPayloads(validate(data),{...event,start:events.cities[0].start},'test',env);assert.deepEqual(jobs.find(j=>j.kind==='organiser').payload.to,[expected[event.id]]);assert.deepEqual(jobs.find(j=>j.kind==='confirmation').payload.to,['alex@example.com']);assert.match(jobs[0].payload.from,/info@chargeout.net/);}});
test('closed and incomplete services refuse registrations without saving or sending',async()=>{for(const changed of [{REGISTRATION_OPEN:'false'},{RESEND_API_KEY:''},{ADMIN_TOKEN:''},{ORGANISER_EMAILS:'{}'}]){const res=await worker.fetch(req(),{...env,...changed},ctx);assert.equal(res.status,503);}assert.equal(env.DB.db.prepare('SELECT count(*) AS n FROM registrations').get().n,0);assert.equal(requests.length,0);});
test('unconfirmed cities and disallowed origins are rejected',async()=>{assert.equal((await worker.fetch(req({...data,city:'perth'}),env,ctx)).status,409);assert.equal((await worker.fetch(req(data,{Origin:'https://attacker.example'}),env,ctx)).status,403);assert.equal(requests.length,0);});
test('failed or wrong-host Turnstile checks never create a registration',async()=>{globalThis.fetch=async()=>Response.json({success:true,hostname:'wrong.example'});assert.equal((await worker.fetch(req(),env,ctx)).status,400);assert.equal(env.DB.db.prepare('SELECT count(*) AS n FROM registrations').get().n,0);});
test('registration stores all three jobs atomically, routes alert and schedules correct Brisbane reminder',async()=>{const response=await worker.fetch(req(),env,ctx);assert.equal(response.status,201);const body=await response.json();assert.equal(body.event.venue,'Port Office Hotel');assert.ok(body.reference);await Promise.all(tasks);const rows=env.DB.db.prepare('SELECT * FROM email_jobs').all();assert.equal(rows.length,3);assert.equal(rows.find(j=>j.kind==='confirmation').status,'sent');assert.equal(rows.find(j=>j.kind==='organiser').status,'sent');const reminder=rows.find(j=>j.kind==='reminder');assert.equal(reminder.status,'pending');assert.equal(reminder.due_at,new Date('2026-11-12T12:15:00+10:00').getTime());const sends=requests.filter(r=>r.url.includes('resend'));assert.equal(sends.length,2);assert.deepEqual(JSON.parse(sends[1].options.body).to,['brisbane-organiser@example.com']);});
test('same-key retry is idempotent and conflicting edits are rejected',async()=>{const a=await worker.fetch(req(),env,ctx);const first=await a.json();await Promise.all(tasks);const b=await worker.fetch(req(),env,ctx);assert.equal(b.status,200);assert.equal((await b.json()).reference,first.reference);assert.equal(env.DB.db.prepare('SELECT count(*) AS n FROM registrations').get().n,1);assert.equal(env.DB.db.prepare('SELECT count(*) AS n FROM email_jobs').get().n,3);assert.equal((await worker.fetch(req({...data,firstName:'Changed'}),env,ctx)).status,409);});
test('email/city duplicates do not send a second set of messages',async()=>{await worker.fetch(req(),env,ctx);await Promise.all(tasks);const response=await worker.fetch(req(data,{'Idempotency-Key':'another-request-key-00000000002'}),env,ctx);assert.equal(response.status,409);assert.equal(env.DB.db.prepare('SELECT count(*) AS n FROM registrations').get().n,1);});
test('admin data is protected and cancellation suppresses queued reminders',async()=>{const response=await worker.fetch(req(),env,ctx);const {reference}=await response.json();await Promise.all(tasks);const url='https://api.example.com/admin/registrations';assert.equal((await worker.fetch(new Request(url),env,ctx)).status,401);const headers={Authorization:`Bearer ${env.ADMIN_TOKEN}`};const listing=await worker.fetch(new Request(url,{headers}),env,ctx);assert.equal(listing.status,200);assert.equal((await listing.json()).registrations.length,1);const cancelled=await worker.fetch(new Request(url+'/'+reference,{method:'PATCH',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({cancel:true})}),env,ctx);assert.equal(cancelled.status,200);assert.equal(env.DB.db.prepare("SELECT status FROM email_jobs WHERE kind='reminder'").get().status,'cancelled');});
test('temporary email failure retries with stable idempotency key and no duplicate jobs',async()=>{globalThis.fetch=async(url,options)=>{requests.push({url,options});return String(url).includes('siteverify')?Response.json({success:true,hostname:'chargeout.net'}):new Response('',{status:503});};await worker.fetch(req(),env,ctx);await Promise.all(tasks);const jobs=env.DB.db.prepare("SELECT * FROM email_jobs WHERE kind!='reminder'").all();assert.ok(jobs.every(j=>j.status==='pending'&&j.attempts===1));const keys=requests.filter(r=>r.url.includes('resend')).map(r=>r.options.headers['Idempotency-Key']);globalThis.fetch=async(url,options)=>{requests.push({url,options});return Response.json({id:'retried-id'});};await processEmails(env,Date.now()+120000);const retried=requests.filter(r=>r.url.includes('resend')).slice(2).map(r=>r.options.headers['Idempotency-Key']);assert.deepEqual(retried,keys);assert.equal(env.DB.db.prepare("SELECT count(*) AS n FROM email_jobs WHERE status='sent'").get().n,2);});
test('permanent provider failure is visible without endless retries',async()=>{globalThis.fetch=async(url)=>String(url).includes('siteverify')?Response.json({success:true,hostname:'chargeout.net'}):new Response('',{status:422});await worker.fetch(req(),env,ctx);await Promise.all(tasks);assert.equal(env.DB.db.prepare("SELECT count(*) AS n FROM email_jobs WHERE status='failed'").get().n,2);});
test('a due reminder is sent once, and expired retry windows require review',async()=>{await worker.fetch(req(),env,ctx);await Promise.all(tasks);const reminder=env.DB.db.prepare("SELECT * FROM email_jobs WHERE kind='reminder'").get();await processEmails(env,reminder.due_at+300000);assert.equal(env.DB.db.prepare("SELECT status FROM email_jobs WHERE kind='reminder'").get().status,'sent');const before=requests.length;await processEmails(env,reminder.due_at+600000);assert.equal(requests.length,before);env.DB.db.prepare("UPDATE email_jobs SET status='pending',due_at=?,first_attempt_at=? WHERE kind='confirmation'").run(Date.now()-1000,Date.now()-24*3600000);await processEmails(env);assert.equal(env.DB.db.prepare("SELECT status FROM email_jobs WHERE kind='confirmation'").get().status,'failed');});

test("manager-only mode queues one alert and no delegate emails", async()=>{env.NOTIFICATION_MODE="organiser-only";const response=await worker.fetch(req(),env,ctx);assert.equal(response.status,201);await Promise.all(tasks);const jobs=env.DB.db.prepare("SELECT kind,payload FROM email_jobs").all();assert.equal(jobs.length,1);assert.equal(jobs[0].kind,"organiser");assert.equal(JSON.parse(jobs[0].payload).reply_to,"alex@example.com");assert.match(JSON.parse(jobs[0].payload).text,/Dietary requirements: vegetarian/);assert.deepEqual(JSON.parse(jobs[0].payload).to,["brisbane-organiser@example.com"]);});
